Fix gpconfig ssh retry undefined param issue. (#15283)
This fix https://github.com/greenplum-db/gpdb/issues/15282

When gpssh retry due to connection failed, will get error like:

NameError: name 'pickled' is not defined
20230329:08:20:21:020634 gpconfig:ip-192-168-216-122:gpadmin-[ERROR]:-name 'pickled' is not defined
Traceback (most recent call last):
  File "/usr/local/gpdb/lib/python/gppylib/commands/base.py", line 278, in run
    self.cmd.run()
  File "/usr/local/gpdb/lib/python/gppylib/commands/base.py", line 555, in run
    self.exec_context.execute(self, pickled=self.pickled)
  File "/usr/local/gpdb/lib/python/gppylib/commands/base.py", line 512, in execute
    self.__retry(cmd)
  File "/usr/local/gpdb/lib/python/gppylib/commands/base.py", line 519, in __retry
    LocalExecutionContext.execute(self, cmd, pickled=pickled)
NameError: name 'pickled' is not defined

Authored-by: Zhang Mingli avamingli@gmail.com