Fix misc python dependencies in build & test (#15732)
Due to the chaos of the python versions in DITROs, we plan to release
gpdb7 with:

- Use the ditro`s default python version (3.6 in el8) for the management
  utilities.
- Use a more advanced python version (3.9) for plpython, so the users
  can benefit from the active python community.

To do that:

- Use `python3` instead of `python` in the build/test scripts, since
  `python` executable is not guaranteed to exist after installation of
  python3.x package.
- Remove mock 1.0.1. mock is specified in the
  `gpMgmt/requirements-dev.txt`. There is no need to have a egg file in
  the repo. And the mock 1.0.1 will fail unit tests with python3.6:

```
======================================================================
ERROR: Test Suite Name|commands.test.unit.test_unit_gp|Test Case Name|test_is_gprecoverseg_running_succeeds|Test Details|
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/build/94afc7d4/gpdb_src/gpMgmt/bin/pythonSrc/ext/install/lib/python3.6/site-packages/mock-1.0.1-py3.6.egg/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/tmp/build/94afc7d4/gpdb_src/gpMgmt/bin/gppylib/commands/test/unit/test_unit_gp.py", line 191, in test_is_gprecoverseg_running_succeeds
    result = is_gprecoverseg_running()
  File "/tmp/build/94afc7d4/gpdb_src/gpMgmt/bin/gppylib/commands/gp.py", line 1635, in is_gprecoverseg_running
    gprecoverseg_pidfile = os.path.join(get_coordinatordatadir(), `gprecoverseg.lock`, `PID`)
  File "/usr/lib64/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not MagicMock
```